### ISSUE TITLE
Subjects: redesign classification

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#15]
@tomasgil123

**Comment by tomasgil123** [comment]
Gdoc con el listado final de materias https://docs.google.com/spreadsheets/d/1cifFOKHDhOXRD0swNloeesk38NGS2CHRTIi1FsgWyQI/edit#gid=0 
Las materias fueron clasificadas en subgrupos segun la tematica y segun el nivel. Por ejemplo, adentro del subgrupo "matematica" estan todas las materias relacionadas con matematica, como son analisis I y II, calculo, matematica, etc. Adentro del subgrupo quimica estan todas las materias relaciondas con quimica, como conceptos basicos de quimica, fundamentos de quimica, quimica organica, quimica inorganica, etc. 
A su vez, a cada materia se le asigno un nivel: universitario, terciario, secundario o primario.
Funcionamiento: si alguien busca "matematica" en el buscador le aparecen todas las materias del subgrupo. Si alguien busca "calculo" le aparece calculo I y II.
La idea es darle mas versatilidad al sistema de busqueda. Que les parece? @nicogarcia @federicojasson

**Comment by federicojasson** [comment]
La idea es interesante. La implementación hay que analizarla más.
¿Qué opinás @nicogarcia ? ¿Se podría hacer fácilmente la búsqueda con Selectize si agregamos un campo "category"?

**Comment by nicogarcia** [comment]
Ya vengo pensando en la alternativa de implementar nosotros la caja de búsqueda para tener mas control y personalizarla, creo que en algún momento lo vamos a tener que hacer, así que mejor hacerlo ahora teniendo en cuenta que es una parte muy importante del sistema.
Podemos usar una librería de autocomplete y partimos de ahí, ¿qué te parece?

**Comment by federicojasson** [comment]
Dale, agrego entonces la categoría.
¿Cómo manejamos la categoría? ¿Enum? ¿String? ¿Como una tabla más?

**Comment by nicogarcia** [comment]
¿Depende de la búsqueda? Veamos por chat.

**Comment by tomasgil123** [comment]
![form oferente](https://cloud.githubusercontent.com/assets/14185059/9794317/d45708ae-57c0-11e5-8f5d-2637dd064d77.png) En el formulario de registracion del oferente pensaba en preguntarle por las materias de esa forma, dandole la posibilidad de que seleccione el nivel y que solo pueda elegir materias de los niveles seleccionados. Es jodido de hacer?

**Comment by tomasgil123** [comment]
![takelessons 1](https://cloud.githubusercontent.com/assets/14185059/9796511/edd98250-57cc-11e5-8e0d-08a2b9b18f29.png)
Que tan jodido es poner una box donde la persona pueda indicar la materia que quiere dar y no encontro?

**Comment by nicogarcia** [comment]
Es muy importante la selección de materias, porque tenemos que hacerlo lo menos engorroso posible. Yo dejaría esto para un hangout. ¿Les parece?

**Comment by tomasgil123** [comment]
Dale

**Comment by nicogarcia** [comment]
Cierro este issue y abro otro en blanco con la especificación.
