### ISSUE TITLE
Add limit to related teachers

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#22]
Limit to any reasonable number, and add it to properties please.

I have seen the TODO ;)

**Comment by federicojasson** [comment]
Should we use a Pageable to allow the client to define the number of related teachers the service returns?

**Comment by nicogarcia** [comment]
Yes I think that's the solution, but I thought it was easier work, let's pospone this for the next milestone, sorry.

**Comment by federicojasson** [comment]
It's not hard to add the pagination. The hard thing is to actually implement a "related teachers" logic.

**Comment by nicogarcia** [comment]
That's right, if it's not a problem for you, go ahead and add pagination. Related teachers is future work, I' opening an issue for that.
