### ISSUE TITLE
API: change URLs and HTTP methods to adapt services to REST

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-server#23]
I propose to make the following changes:

-------------------

Current:   POST /students/me/favorite-teachers
Change to: PUT /students/me/favorite-teachers/{id}

Reason:
The "add favorite teacher" operation is idempotent (https://github.com/nicogarcia/classes-web-server/blob/master/src/main/java/com/classes/app/student/StudentServiceImpl.java#L23).
The teacher's ID should be sent as parameter because PUT operations must reference an entity in the collection (http://stackoverflow.com/questions/630453/put-vs-post-in-rest).

-------------------

Current:   DELETE /teachers/{id}/reviews
Change to: DELETE /teachers/{id}/reviews/mine

Reason:
The DELETE operations must reference the entity being deleted.
Since we're already using "me" to refer to the logged-in user, it's only logical to use "mine" to refer to a logged-in user's resource (her review in this case).

-------------------

Current:   POST /teachers/{id}/reviews
Change to: PUT /teachers/{id}/reviews/mine

Reason:
The "create review" operation is idempotent (https://github.com/nicogarcia/classes-web-server/blob/master/src/main/java/com/classes/app/teacher/TeacherServiceImpl.java#L46).
"mine" should be added because PUT operations must reference an entity in the collection (this is consistent with the DELETE operation above).

-------------------

Thoughts? @nicogarcia

**Comment by nicogarcia** [comment]
No suggestions. Assign me a new issue in client referencing this one, please.
