### ISSUE TITLE
Create verification email template

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#37]

**Comment by sergioam90** [comment]
![123123](https://cloud.githubusercontent.com/assets/13783674/10155243/21a1e39a-6649-11e5-84cb-aaffac755ff1.jpg)

**Comment by tomasgil123** [comment]
![mails validacion 4](https://cloud.githubusercontent.com/assets/14185059/10155272/79b54d6a-6649-11e5-9fb9-63b2f1dd3a54.png)
![mails validacion 5](https://cloud.githubusercontent.com/assets/14185059/10155273/79f588f8-6649-11e5-8b8f-7b3f9ad86d02.png)

**Comment by tomasgil123** [comment]
Hola, (nombre):
Gracias por querer enseñar en Upclaz! Para seguir con el proceso de registracion, solo tenes que confirmar que tenemos tu direccion de correro electronica correcta.
Boton que dice: Confirma tu correo electronico

**Comment by sergioam90** [comment]
No se si van a poder usar el nombre para meterlo en el email de confirmacion, hay que preguntarle a Fede

**Comment by tomasgil123** [comment]
Ah ok. De ultima solo se pone el "hola" y listo. @federicojasson

**Comment by sergioam90** [comment]
Decime donde la pongo o si te la mando a vos Fede

![123123](https://cloud.githubusercontent.com/assets/13783674/10155402/3203e2ea-664b-11e5-8a78-9f8bf5538b89.jpg)

**Comment by tomasgil123** [comment]
La frase que iria seria esta, para que coincida con lo que dice el boton: "Hola, gracias por querer enseñar en Upclaz! Para seguir con el proceso de registración, solo tenes que confirmar que tenemos tu dirección de email correcta." Dejalo aca y cuando fede lo necesite te lo pide

**Comment by nicogarcia** [comment]
Excelente Sergio ;)

**Comment by nicogarcia** [comment]
Malas noticias, tuve que sacar la imagen porque no la mostraba. Quedo bastante mas feo. 
Cambie algunos textos y errores en palabras.
Usé esto para probar: https://putsmail.com/tests/new 
Y esto para meter inline los style para mayor compatibiliad: https://putsmail.com/inliner

**Comment by tomasgil123** [comment]
Si no manda la imagen, ya fue. Mandamos solo el texto que habiamos armando con el boton.

**Comment by nicogarcia** [comment]
Ya se puede probar.

**Comment by federicojasson** [comment]
El nombre se puede poner (y toda otra información del usuario).
¿Lo de las imágenes lo pudieron resolver? Tal vez puedo meter mano.

**Comment by tomasgil123** [comment]
Yo lo vi sin imagen y no quedo tan mal, zafa. Lo de agregar la imagen lo consideraria algo no prioritario.

**Comment by nicogarcia** [comment]
Estuve un buen rato con las imágenes, no creo q valga la pena (algunos clientes directamente no las muestran y queda peor un alt="" que un titulo de una y listo como esta ahora)

**Comment by federicojasson** [comment]
¿Cómo probaste? Acordate que tenés que hacer attach.
El logo creo que es clave en el mail.

**Comment by nicogarcia** [comment]
Probé con link. En Outlook no se ve, incluso llega a spam, si querés podes ver eso antes.

**Comment by federicojasson** [comment]
Con link NO DEBE funcionar.
Lo agrego a mi TODO list

**Comment by nicogarcia** [comment]
En gmail debería andar con links.

**Comment by federicojasson** [comment]
Los links (en general) se deshabilitan para evitar el tracking: https://en.wikipedia.org/wiki/Email_tracking#Email_marketing_and_tracking
