### ISSUE TITLE
Heroku fails to load app due to high load time

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#46]
Maybe we should load subjects data manually using a postgres client to avoid sync data loading.

**Comment by federicojasson** [comment]
Podría hacerse manualmente. Lo ideal sería tener un addon que permita guardar el seed y ejecutarlo manualmente (algo así como un DataClip para escritura). No encontré en Heroku cómo hacerlo, si podés chequealo.
