### ISSUE TITLE
Check database creation in heroku

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#54]
Algo parece estar mal en la base de datos. Fijate.

¿Esta bien que usemos import.sql? 
Me parece que eso lo tendríamos que cargar nosotros directo a la bd. La app no debería "tocar" la base de datos para crearla.

**Comment by federicojasson** [comment]
Dejalo abierto el issue. Mientras estemos en desarrollo es mejor me parece.

**Comment by federicojasson** [comment]
Duplicado: #61
