### ISSUE TITLE
Format fixed to jpg in cloudinary client directive

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-server#57]
"cl-image ... format="jpg"..."

Los png no cargan, error (Unauthorized)

**Comment by federicojasson** [comment]
No debería haber PNG (¿en qué circunstancia pasó esto?) porque al subir las imágenes las transforma a JPG. De todos modos esto es lo que está solucionando el support de Cloudinary (que funcione sin indicar el formato).

**Comment by nicogarcia** [comment]
Subí un png y fallo al mostrarlo

**Comment by federicojasson** [comment]
Ya está arreglado
